### ISSUE TITLE
Why do using features from mask_rcnn_X_101_32x8d for object features extraction task worked well in case of tracking?

### ISSUE THREAD

**Issue by dmitmatveev** [Lijun-Yu/zero_virus#6]
Hi Lijun Yu, thanks for your great work. Your methods of tracking and routes modeling interested me a lot.

May you tell me, why using features from ```mask_rcnn_X_101_32x8d``` for object features extraction task worked really well in case of tracking vehicles? I was really surprised by the tracking quality, because you didn't train and **just pick up COCO pre-trained detection model.** Is this such as specific of the model?
As i understood, ```mask_rcnn_X_101_32x8d``` is mainly COCO detector while solving tracking task is not expected, even that fact the detector was not pretrained for ReID task. 

The question could be useful to understand:
1. How to train ```mask_rcnn_X_101_32x8d``` to improve tracking (to improve features extraction for ReID)?
2. Could i use another COCO pre-trained **detection** model (CenterNet, YOLO) and take their features? 
3. Or would be better to turn to specific solutions like Joint Detection and Embedding (JDE) models? *(In this case JDE-model is usually pre-trained of MOT-datasets with people only, so **training** is usually **needed for vehicle tracking**)*

Thank you!

**Comment by Lijun-Yu** [comment]
Hi MistyDi, thank you for your interest in this work!

The reason for reusing detection features for tracking is mainly efficiency concerns. The tracking algorithm takes in the bounding box position and feature embedding of each object to associate them. Better features, especially those trained for ReID task, will very likely improve the tracking performance. But using separate features for tracking often largely increases the computation cost.
Earlier tracker such as SORT uses no features but solely bounding boxes, while later ones such as deep-SORT uses pretrained ReID features. Using pretrained detection features would expect a reasonable performance between these two.

1. You may try adding a separate output branch for ReID features which takes the detection features as input. This branch can be trained on some ReID tasks, with the remaining part of the model frozen.
2. Yes, but due to different architectures, you may need to come up with a different way to take the features corresponding to the bounding box region.
3. With sufficient training data, the joint solutions could be better. But if data is not available, it may actually depend on the generalizability of the model trained on another dataset.
